Orfium/orfium-github-actions

.github/workflows/fe-combine-dependabot-prs.yml, README.md
This PR introduces the `FE Combine Dependabot PRs` sharable workflow.
It has been [tested in VH](https://github.com/Orfium/video-hunter-frontend/actions/runs/2239436006) and it works.
=> feat: add FE combine dependabot workflow

.github/workflows/trigger-release-pr.yml
Fix `SyntaxError: Unexpected token ';'` when running the workflow.
=> fix: fix release pr trigger javascript unexpected token

.github/workflows/deploy-frontend.yml, .github/workflows/teardown-frontend.yml
In this PR we add  a check if the pr contains the label dependencies, then we mustn't create a Review App.
=> [DEVOPS-800] Feat/ Disable Dependabot Review Apps 

.github/workflows/deploy-frontend.yml
Disabling dependabot review apps to avoid maxing out infra limitations.
=> [DEVOPS-800] Feat/disable dependabot

.github/workflows/fe-combine-dependabot-prs.yml
[ticket](https://orfium.atlassian.net/browse/FE-25) Dependabot was failing without any message or indication which was the problem branch. Also, it didn't exclude the branch with the conflict and was failing all together.
Now, it creates the Combined PR with whatever branches are not failing.
=> [FE-25] feat/ Extend Dependabot Workflow 

.github/workflows/deploy.yml
=> Fixes typo

.github/workflows/deploy.yml
=> Uses space as a delimiter instead of a comma

.github/workflows/deploy.yml
=> Removes invalid description property

.github/workflows/deploy.yml
=> Adds missing GITHUB_OUTPUT

.github/workflows/test.yml
=> ci: remove update of coverage badge on test.yml

.github/workflows/build-and-push.yml
=> fix: always build production images

.github/workflows/test.yml
=> fix(test): use proper cache-from directive for caching

.github/workflows/sonarqube.yml
* Apply fix in sonarqube workflow. (Resolves #38)
=> apply fix in sonarqube workflow

.github/workflows/gather-migrations-reqs.yml, .gitignore
[BEC-264](https://orfium.atlassian.net/browse/BEC-264)
[BEC-264]: https://orfium.atlassian.net/browse/BEC-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(migrations): create gather-migrations-requirements reusable workflow

.github/workflows/deploy-frontend.yml
=> Use new frontend template

.github/workflows/test-e2e.yml
- Add end to end tests workflow (https://orfium.atlassian.net/browse/CDT-75) 
example use : https://github.com/Orfium/universal-catalog-mapper/actions/runs/4246636800/jobs/7383777471
=> feat: add end to end tests workflow [CDT-75]

.github/workflows/deploy-frontend.yml
=> Short circuit response headers policy creation

.github/workflows/build-and-push.yml, .github/workflows/deploy.yml, .github/workflows/gather-migrations-reqs.yml, .github/workflows/teardown.yml, README.md
https://orfium.atlassian.net/browse/DEVOPS-932
Sample PR that also test backwards compatibility: https://github.com/Orfium/todo/pull/31
Old config: https://github.com/Orfium/todo/actions/runs/4304379086
New config: https://github.com/Orfium/todo/actions/runs/4305182091
=> [DEVOPS-932] Make infra folder path configurable

.github/workflows/deploy.yml, .github/workflows/teardown.yml, docs/CONTRIBUTING.md, docs/pull_request_template.md
Example Deployment: https://github.com/Orfium/todo/actions/runs/4552826161
Example Teardown: https://github.com/Orfium/todo/actions/runs/4552935505
=> [DEVOPS-942] Remove GitHub envs from lifecycle and simplify workflows

.github/workflows/precommit.yml
[BEC-308](https://orfium.atlassian.net/browse/BEC-308)
[BEC-308]: https://orfium.atlassian.net/browse/BEC-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: revert run precommit on diffs on PR

.github/workflows/test-e2e.yml
- Introduce TESTRAIL env vars for test-e2e job
=> ci(test-e2e.yml): introduce new env vars [CDT-163]

.github/workflows/bump.yml
Use latest version of semantic release as output. .releaserc file must be modified as in https://github.com/Orfium/sso-facade/pull/811/files with the semantic-release/exec plugin.
@johnecon @anmarkoulis
=> feat: output latest version in bump.yml

.github/workflows/test.yml
=> feat: Allow ECR login in unit tests [RC-2196]

.github/workflows/update-precommit-deps.yml
[BEC-404](https://orfium.atlassian.net/browse/BEC-404)
With this PR a reusable workflow for updating precommit dependencies is being introduced. 
[BEC-404]: https://orfium.atlassian.net/browse/BEC-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: create a reusable workflow for updating dependabot deps

.github/dependabot.yml
=> Add dependabot for GitHub Actions' version updates

.github/CODEOWNERS
=> Add BE Staff to the CODEOWNERS file as they should have a say to their workflows

.github/workflows/gchat-notification.yml
=> [DEVOPS-1178] Add GChat Notification reusable workflow

.github/workflows/gchat-notification.yml
=> Add support for pull_request and pull_request_target triggers

.github/workflows/setup-fernet-key.yml, .github/workflows/sync-airflow-dags.yml
As a result of our migration to the Airflow template, we have some actions that could be reused. Initial versions exist in the RC service, but other teams might need this.
=> feat: Add Airflow actions [RC-2442]

.github/workflows/sync-airflow-dags.yml
=> feat: Allow delete on DAGs bucket [RC-2441]

.github/workflows/check-init-deploy.yml
[BEC-459](https://orfium.atlassian.net/browse/BEC-459)
[BEC-459]: https://orfium.atlassian.net/browse/BEC-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: create check init deploy reusable workflow

.github/workflows/run-command-v2.yml
=> fix: identify properly the stack name using the environment_suffix

.github/workflows/setup-fernet-key.yml
=> Fix --stack_name aws cli command option, and change it to --stack-name

.github/workflows/setup-fernet-key.yml
=> fix: check if secret exists and not only if stack exists before creating a new fernet

.github/workflows/deploy-frontend-monorepo.yml, .github/workflows/teardown-frontend-monorepo.yml
This new workflow is needed for the FE monorepo and has been already tested https://github.com/Orfium/frontend-fusion
=> feat: define workflows for monorepo with turbo

.github/workflows/deploy-frontend-monorepo.yml
This PR changes yarn to pnpm which is the package manager that our monorepo will use. This is an expanded feature of https://github.com/Orfium/orfium-github-actions/pull/117
=> feat(frontend): adding pnpm

.github/workflows/sonarqube.yml
We are adding a copy of the sonarqube workflow that uses the neo-runner sef hosted runner, for running sonarqube workflows on neo repos
=> fix: CD-3676 enhance sonarqube.yml with runner param

.github/workflows/swaggerhub.yml
This reverts commit a6bbde85e64ce9c78b210c11b85ac75163b6a5f1.
=> Revert "feat: remove swaggerhub lint temporarily until gobinaries.com is up"

.github/workflows/README.md, .github/workflows/get_codeartifact_consuming_info.yml, .github/workflows/get_codeartifact_publishing_info.yml, .github/workflows/poetry_code_artifact_publish.yml, .github/workflows/register-deploy-to-getdx.yml, .github/workflows/register-deregister-sso-callback-url.yml, .github/workflows/twine_code_artifact_publish.yml
=> feat: move workflows from private actions repo

.github/workflows/README.md, .github/workflows/poetry_code_artifact_publish.yml, .github/workflows/uv_code_artifact_publish.yml
=> Fix calls to previous github-actions private repository

.github/workflows/run-dbt-commands.yml
[IPL-2024]
[IPL-2024]: https://orfium.atlassian.net/browse/IPL-2024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [IPL-2024] Add workflow for running dbt commands in the DBT Service
