Orfium/orfium-github-actions

- .github/workflows/trigger-release-pr.yml
Fix GH action `trigger-release-pr.yml` error.
https://github.com/Orfium/matching-api/actions/runs/3087939249
update: `workflow_dispatch` -> `workflow_call`
> fix: fix trigger release pr workflow call

- .github/workflows/trigger-release-pr.yml
- README.md
* Fix inputs access on workflow_call of trigger-release-pr.yml (reusable workflow). Based on Github's official documentation [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow)
* Update documentation.
> fix: fix inputs access on workflow_call of trigger release pr

- .github/workflows/deploy-frontend.yml
- .github/workflows/teardown-frontend.yml
- .github/workflows/trigger-release-pr.yml
Replace set-output with echo "var=value" >> $GITHUB_OUTPUT
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ci: replace deprecating set-output with environment files

- .github/workflows/deploy.yml
- README.md
Address the following issues:
- Instead of always using the aws-deploy.yml file for deployment, an existing CloudFormation template should be allowed (S3 bucket URL or local) 
- Make common.env file optional  (if it’s not already)
- Make dynamic parameters optional
- Make env_parameters.json compatible with aws cloudformatio deploy json parameters file
Modifications/Enhancements:
1. Main template has been made optional and without file extension
2. Common environment file is now optional
3. Dynamic Parameters workflow input has been made optional
4. Environmental parameters now support both a key-value json format and a cloudformation/codepipeline format with a parent "Parameters" key
> [DEVOPS-865] Enhance deploy workflow based on ticket comments

- .github/workflows/deploy-frontend.yml
This PR add the support for new node 18.14 that introduce latest `npm` `9.3.1`. By adding the latest npm, the `always-auth` is no longer used and is set by default. That is why we silently fail with a message
For older versions with older `npm` this should work as expected
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.14.0
> fix: update always-auth for new node 18.14 and support old

- .github/workflows/test-e2e.yml
- Add test report viewer in e2e tests reusable action (example https://github.com/Orfium/universal-catalog-mapper/actions/runs/4894297717/jobs/8738554725)
> ci/add e2e tests report visualisation [QA-518]

- .github/workflows/test-e2e.yml
- Handle cases where previous steps have failed. In those cases the reporting step was skipped (ie https://github.com/Orfium/universal-catalog-mapper/actions/runs/4990857929/jobs/8936890476) 
example: https://github.com/Orfium/universal-catalog-mapper/actions/runs/4992736350/jobs/8941068045
> fix: fix e2e-tests reports when a step fails [CDT-245]

- .github/workflows/swaggerhub.yml
[BEC-337](https://orfium.atlassian.net/browse/BEC-337)
[BEC-337]: https://orfium.atlassian.net/browse/BEC-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: publish swaggerhub projects as private

- .github/workflows/build-local-images.yml
The `build-local-images` action will now push instead on ECR using the `local` tag both when merging to main and local. This image can then be used on next deployments as a caching layer to speedup the build process.
[BEC-302](https://orfium.atlassian.net/browse/BEC-302)
[BEC-302]: https://orfium.atlassian.net/browse/BEC-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: use updated action for build local images using caching

- .github/workflows/build-and-push.yml
[BEC-301](https://orfium.atlassian.net/browse/BEC-301)
The `build-and-push` action will now push instead of the commit sha only to the `stable` tag when something is merge to main. This image can then be used on next deployments as a caching layer to speedup the build process.
[BEC-301]: https://orfium.atlassian.net/browse/BEC-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add caching in reusable workflows on build and push step

- .github/workflows/dependabot-approve-and-set-auto-merge.yml
[BEC-421](https://orfium.atlassian.net/browse/BEC-421)
Create a reusable workflow that will check if the PR is opened from dependabot[bot] or github-actions[bot] and automatically approve it and set it for automerge once the branch protection guidelines are OK.
Workflow has been tested in https://github.com/Orfium/fastapi-orfium-utils/pull/140 and the pipeline is https://github.com/Orfium/fastapi-orfium-utils/actions/runs/6308938765.
We plan to use it in libraries and not products in order to automatically merge dependabot PRs. After all, all we do is to check the pipeline and manually merge
[BEC-421]: https://orfium.atlassian.net/browse/BEC-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: create workflow for approve and set auto merge of dependabot PRs

- .github/workflows/test-e2e.yml
Update all references for Testrail Password and replace it with Testrail CI API key so that when password rotation takes place in Testrail, our CI jobs are not affected.
A new global GitHub secret has been added in GitHub named `TESTRAIL_CI_API_KEY`
The same secret has also been added as a global Jenkins credential.
[Jira ticket QA-598](https://orfium.atlassian.net/browse/QA-598)
> chore: replace TESTRAIL_PASSWORD with TESTRAIL_CI_API_KEY [QA-598]

- .github/workflows/build-and-push-v2.yml
- .github/workflows/build-and-push.yml
- .github/workflows/build-local-images-v2.yml
- .github/workflows/build-local-images.yml
- .github/workflows/precommit.yml
- .github/workflows/swaggerhub.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
[BEC-464](https://orfium.atlassian.net/browse/BEC-464)
During the past we have pinned the version of buildkit to be used together with the [setup-build-action](https://github.com/docker/setup-buildx-action). After the issue on precommit we have identified that it is about time to unpin this one as the proper version is now being used. 
[BEC-464]: https://orfium.atlassian.net/browse/BEC-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use latest moby buildkit version

- .github/workflows/extract-jira-id.yml
- README.md
We need to get the Jira ticket ID inside the gitHub action of the tests to link it with the TestRail reports.
This action tries to find a Jira ticket ID in the format of `PRJ-123` either in the PR title or in the branch name (in that order).
The action stores the job output in a variable called `jira_ticket_id`.
|  PR title | Branch name  |
|---|---|
|  PRJ-123 My PR title | PRJ-123-my-branch-name  |
|  [PR-123] My PR title |  PRJ-123/my-branch-bane |
Practically, any character before or after the correct format is allowed.
[PR-123]: https://orfium.atlassian.net/browse/PR-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-627] Add action to extract the Jira ticket ID from a PR

- .github/workflows/test-e2e.yml
Remove `Publish test results to TestRail` and all related secrets and mentions. 
https://orfium.atlassian.net/browse/QA-647
If the needed testmo params or the token is not provided to the reusable action the publish results to testmo step is skipped(Tested using onflict-grail)
- Token not set: https://github.com/Orfium/conflict-grail/actions/runs/9759933353/job/26937762270?pr=718
- Param missing: https://github.com/Orfium/conflict-grail/actions/runs/9759731948/job/26937370457
> feat(e2e-tests): Remove `Publish test results to TestRail` step

- .github/workflows/precommit.yml
- .github/workflows/swaggerhub.yml
- .github/workflows/test-e2e.yml
- .github/workflows/test.yml
As we currently do in other reusable workflows (e.g https://github.com/Orfium/orfium-github-actions/blob/8fbdccb4c8aeb4f7f571bb8e3a609f926bfcd42c/.github/workflows/build-local-images-v2.yml#L115 ) we can add the docker target as input of the reusable workflow instead of hardcoding it as local or something else. The reason behind this is that some teams may have different name of docker target layer.
> Pass docker target from workflow calls inputs

- .github/workflows/deploy-frontend-monorepo.yml
This PR introduces a fix for building the frontend. Currently, we need to build processes, one to build without the sourcemaps to upload to AWS and a second one with sourcemaps for SENTRY. 
With this proposal there is going to be one build for all with the sourcemaps but the deployment will exclude them
changes are based on
https://docs.aws.amazon.com/cli/latest/reference/s3/#use-of-exclude-and-include-filters
introduce a better release tag for sentry with the app name and version e.g `earnings-0.0.1`
> fix(monorepo): keep one build with exclusion in map files for s3

- .github/workflows/deploy-frontend-monorepo.yml
This PR adjusts the node heap size to 4Gb for the build step only, since rights cloud needs more memory when generating the build with sourcemaps.
Related info: https://github.com/actions/runner-images/issues/70
> fix(monorepo): adjust node heap size for build

- .github/workflows/deploy-frontend-monorepo.yml
This once more solves the issues we are facing with sentry. We solved in the past how we can upload the current version but it did;t worked when a new release was going to be made as the release workflow is separated from the main CI workflow. 
With this solution we dry-run the release step so we can calculate the version to upload to sentry.
> fix: release of the sentry in monorepo

- .github/workflows/update-precommit-deps.yml
This pull request updates the `.github/workflows/update-precommit-deps.yml` file to enhance the pre-commit autoupdate workflow by adding support for extra arguments, improving caching, and using a GitHub App token for authentication.
* **Added support for extra arguments**: Introduced a new input parameter `extra-args` to allow passing additional arguments to the `pre-commit autoupdate` command.
* **Improved caching and setup**:
- Replaced the `vrslev/pre-commit-autoupdate` action with a custom workflow that includes Python setup, caching for pre-commit and pip, and manual installation of `pre-commit`.
- Added a cache key based on Python version and `.pre-commit-config.yaml` hash to optimize caching.
> fix: fix precommit automatic deps

- .github/workflows/swaggerhub.yml
This pull request includes a minor change to the `.github/workflows/swaggerhub.yml` file. The change comments out the step that uses the `stoplightio/spectral-action` for linting Swagger files, effectively disabling it for now.
* Workflow adjustments:
* [`.github/workflows/swaggerhub.yml`](diffhunk://#diff-63b71f9e79bf09b89658151c5c49e71fa32b20ce098deefd394f85b39d0ed385L136-R140): Commented out the `stoplightio/spectral-action` step, which previously performed Swagger file linting based on the provided ruleset.
> feat: remove swaggerhub lint temporarily until gobinaries.com is up
